### ISSUE TITLE
Create or load htslib .fai and .gzi index files when using BGZF files

### ISSUE THREAD

**Issue by KwatME** [mdshw5/pyfaidx#126]
Hi,

When I do `samtools faidx file.fa.gz` and then try to use the same `file.fa.gz` file for `pyfaidx`, I get an error saying that `file.fa.gz` is not a valid BGZF file. But when I delete the `file.fa.gz.fai` and then use `pyfaidx`, the error disappears. I believe this is because the `.fai` `pyfaidx` creates is different from `.fai` `samtools` creates.

If this behavior is real, Is it possible to unify the `.fai` of `pyfaidx` and `samtools`? Thoughts?

Kind regards,
Kwat

**Comment by KwatME** [comment]
Follow up: `samtools faidx` fails using the index created from `pyfaidx` as well.
<img width="1137" alt="screen shot 2017-09-13 at 05 04 14" src="https://user-images.githubusercontent.com/7741548/30376387-05013b06-9841-11e7-8b1e-3bd611a1f00e.png">

**Comment by mdshw5** [comment]
I think this is a good idea, and the work to support this is:

1. Store compressed file offsets, which is what it looks like samtools is storing in its .fai, instead of [virtual offsets](https://github.com/biopython/biopython/blob/master/Bio/bgzf.py#L185), which I'm doing in this library
2. Write methods to build and load the .gzi index file that htslib creates, which stores the number of gzipped blocks, and (compressed offset, uncompressed offset) for each block start byte (currently described in https://github.com/samtools/htslib/issues/473)
3. Change `Faidx` logic to use the .fai and .gzi indices in combination to recreate virtual offsets (I think this is what samtools faidx is doing)

**Comment by KwatME** [comment]
I checked the .fai files created from pyfaidx and samtools. They are the same.

**Comment by KwatME** [comment]
Closing this issue assuming that #1701 closes this issue. Thanks :)

**Comment by mdshw5** [comment]
Are you able to test whether the issue is fixed? I’ll look into it as well, but I believe our BGZF indices may still be incompatible with samtools.

**Comment by KwatME** [comment]
I see. When this is in place, please let us know. Thanks @mdshw5

**Comment by mdshw5** [comment]
Re-opening to work on this issue before the end of the year.

**Comment by IPetrik** [comment]
Any progress on this?

**Comment by mdshw5** [comment]
@IPetrik I did do some work on this earlier this year, but never made something that works. I believe I pushed what work I had here: https://github.com/mdshw5/pyfaidx/commit/db7f140ce97905d22c2280601f5234dc67711669. I'll take a look on my local machine and see if there's anything else. I'd really like to get this feature working properly so if you've got ideas please share.

**Comment by mdshw5** [comment]
@IPetrik Forget me previous comment. I have some work on my local machine that's completely different. I'll update the `samtools_bgzf_compatibility` branch with what I have.

**Comment by mdshw5** [comment]
I've opened a PR with the work for this issue in #164. If I have some time this summer I'll come back and keep working - it doesn't seem like there's much left to do except finish testing the GZI packing/unpacking and implementing methods to create and read the on-disk format.
