### ISSUE TITLE
Fasta to Bed

### ISSUE THREAD

**Issue by atfields** [mdshw5/pyfaidx#133]
Hi Matt,
I recently saw a post of your's (https://www.biostars.org/p/191052/) and thought I would try it out. It worked like a charm, but the bed file output started at 1 instead of zero. I am new to bed files so I am unsure if a sequence of 1000 bases should be listed as 0 1000 or 0 999, but from what I have seen, they all start at 0. Thanks for your help.
Regards,
Andrew

**Comment by mdshw5** [comment]
Thanks so much for reporting this! It was quite a silly mistake since BED coordinate are definitely [0, 1) and not (1, 1) as I had implemented this feature. 

Your example is almost correct - a sequence of 1000 bases starting at 1 would be [1, 1000] in 1-based open coordinates and [0, 1000) in BED half-open coordinates. That is, the end coordinate is excluded in BED format. See http://genome.ucsc.edu/blog/the-ucsc-genome-browser-coordinate-counting-systems/

**Comment by atfields** [comment]
Hi Matt,

Thanks so much for the fix and the insight!

Regards,
Andrew
