### ISSUE TITLE
Parser breaks if FASTA file does not contain >

### ISSUE THREAD

**Issue by Benjamin-Lee** [mdshw5/pyfaidx#144]
Ok this is a weird one: I'm at a hackathon and they handed us "mystery genomes" that were FASTA files with the comment line removed. I tried to use pyfaidx (through [squiggle](github.com/lab41/squiggle)) and got this error:

```
  File "/Users/BenjaminLee/Desktop/Python/Research/hackseq18/env/lib/python3.6/site-packages/pyfaidx/__init__.py", line 990, in __init__
    build_index=build_index)
  File "/Users/BenjaminLee/Desktop/Python/Research/hackseq18/env/lib/python3.6/site-packages/pyfaidx/__init__.py", line 423, in __init__
    self.build_index()
  File "/Users/BenjaminLee/Desktop/Python/Research/hackseq18/env/lib/python3.6/site-packages/pyfaidx/__init__.py", line 573, in build_index
    rname, rlen, thisoffset, clen, blen))
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by mdshw5** [comment]
Well, it's not a FASTA file without the description line. Are we talking about a file that starts with a semicolon ([like this example](https://en.wikipedia.org/wiki/FASTA_format#Original_format_&_overview))? In that case I could see adding support for FASTA comments. 

If we're talking about file that just contain sequence and no comments or identifiers I doubt there's an indexing strategy for these, since a multi-FASTA file would have no record separator for multiple entries.

If you can provide a bit more detail about how you'd like this supported we can go from there. Thanks!

**Comment by Benjamin-Lee** [comment]
Ideally, it would parse it as normal. That being said, I understand if you don't think that supporting non properly formatted FASTA files is within the scope or even advisable for this project (we recently realized that Biopython doesn't support it either and *fails silently*). If so, could we maybe add a specific warning if no `>` is found rather than a generic error?

**Comment by mdshw5** [comment]
Definitely adding better exceptions would be great. Can I have an example of the file format in question?

**Comment by Benjamin-Lee** [comment]
Sure! The exact file in question can be viewed [here](https://github.com/SweetiePi/bioncd-hackseq/blob/d00f1e6bc5098057be145e42b949205581bee9b5/test_dataset/mysteryGenome_1.fasta).

Basically instead of:
```
> description
ATGGACAGTA...
GATAGATACC...
```
it was getting passed:
```
ATGGACAGTA...
GATAGATACC...
```

**Comment by mdshw5** [comment]
I've added a case for handling files with no valid description lines and pushed a new release (https://github.com/mdshw5/pyfaidx/releases/tag/v0.5.5.1) that should be on PyPI in a few minutes.

**Comment by Benjamin-Lee** [comment]
Thanks a ton!
