### ISSUE TITLE
Cannot use FastaVariant without genotype

### ISSUE THREAD

**Issue by victorlin** [mdshw5/pyfaidx#152]
I am trying to generate a consensus with the ClinVar VCF file (FTP link: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar_20190715.vcf.gz).
However, the file does not contain genotype information (no samples). This seems to trigger an IndexError while parsing in `__init__.py` ([line 1111](https://github.com/mdshw5/pyfaidx/blob/22579e/pyfaidx/__init__.py#L1111)).

I'm fairly new to working with VCF files in general - please let me know if I'm overlooking anything.

**Comment by mdshw5** [comment]
This might be the wrong tool for the task. Currently, `FastaVariant` only incorporates genotypes from individual samples in a VCF, and only SNPs and MNPs, not indels (see #84). If you're trying to add ClinVar alleles prior to alignment, I might suggest you use something like [hisat2](https://ccb.jhu.edu/software/hisat2/index.shtml) to build a graph-based index. Otherwise, if you want to make a consensus FASTA from this VCF, I think [FastaAlternateReferenceMaker](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_fasta_FastaAlternateReferenceMaker.php) will do the trick.

**Comment by victorlin** [comment]
Thanks for the pointers. I'll look into the other tools you've mentioned.
