### ISSUE TITLE
27 tests fail on `=pyfaidx-0.7.2.1`

### ISSUE THREAD

**Issue by TheChymera** [mdshw5/pyfaidx#208]
Full build log here: https://ppb.chymera.eu/061324.log

Any ideas what could be wrong? I know that the package formerly used nose, is this an issue arising from work-in-progress test infrastructure transition?

**Comment by mdshw5** [comment]
This package now uses `pytest`, and so the test runners are slightly different now. You can see the output from a recent CI run [here](https://github.com/mdshw5/pyfaidx/actions/runs/4195765940/jobs/7275775478#step:11:1). From glancing at your log file it looks like the error message are due to biopython not being installed. The biopython package is required for all "bgzf" tests, and so these should all be skipped. I'm not sure why your testing infrastructure is running the skipped tests though.
