### ISSUE TITLE
Orientation attribute is None for complement seqs

### ISSUE THREAD

**Issue by handstad** [mdshw5/pyfaidx#73]
Orientation attribute is None for complement sequence objects, but I assume the correct  value is `-1`.

```python

from pyfaidx import Fasta
f = Fasta("/path/to/human_g1k_v37_decoy.fasta")
s = f[1][10000:10005]
s_complement = s.complement

s.orientation
```
is equal to `1` whereas

`s_complement.orientation` is `None`.

**Comment by mdshw5** [comment]
Hey @handstad. Thanks for raising this issue. It actually caught me off-guard and I had to look back through my reasoning about the `Sequence` interface design. I was trying to mimic (as much as reasonable) the interface to the "pygr" project. The API for the [SeqPath](https://github.com/ctb/pygr/blob/master/doc/rest/reference/sequence.rst#a-pythonic-sequence-model) class provides the prototype for my `orientation` method:
>orientation: `SeqPath` carefully represents relationships between intervals on opposite strands of a double-stranded nucleotide sequence. A `SeqPath` object knows whether it is an interval on the forward or reverse strand. Pygr provides a number of operations for manipulating and comparing intervals of different orientations. For example, -s yields the interval of the opposite strand that is base-paired to interval s...
`-s` is equivalent to `s[::-1].complement`, and so this means that only the reverse complement is considered to be on the bottom strand. This makes biological sense and is the way I'd like to keep things. If you have strong feelings about this, I would consider hearing about your use case and why an interface change would help :). Since the pygr project looks dead, maybe @ctb would chime in about the interface design?

**Comment by handstad** [comment]
Aha, I have probably misunderstood. I haven't used pyfaidx much yet, and I was thinking about the reverse complement, but in order to get that, I have to use both the `reverse` and the `complement` methods, or as also in pygr, use the minus operator, right? Sorry for the confusion, I was a bit too quick with reporting this.


But while I am at it, could you explain if the reverse complement coordinates are correct if I create the Fasta object instance with the one_based_attributes=False ?
```python
f = Fasta("/path/to/human_g1k_v37_decoy.fasta", one_based_attributes=False)
s = f[1][10000:10005]
s_reverse_complement = -s
s_reverse_complement
```

Returns the short interval of `>1:10004-10001 (complement)` , but I was perhaps expecting 10004-9999 or something like that. Without `one_based_attributes=False`, it seems to work as expected.

If getting the reverse complement (again) of that s_reverse_complement:

```python
scc = -s_reverse_complement
scc
scc.orientation
```

returns scc positions as `10008-9997`, but I was expecting `10000-10005` as in the original `s` and the `scc.orientation` then is `None`. Here it seems to be similar problems without `one_based_attributes=False`.

Not that it is probably used very often, but should not the reverse complement of a reverse complement return the original sequence?

**Comment by mdshw5** [comment]
> Not that it is probably used very often, but should not the reverse complement of a reverse complement return the original sequence?

Yes, and that is probably a bug that I can fix :)
