### ISSUE TITLE
zero-based indexing is inconsistently applied in Fasta

### ISSUE THREAD

**Issue by ihaque** [mdshw5/pyfaidx#74]
Setting `one_based_attributes=False` on a `Fasta` object does not propagate indexing operations properly down to the underlying Faidx or Sequence objects.

Given the following test data file:

```
>test_chrom
ACGTACGTACGTACGTACGTACGT
```

and using pyfaidx @ 6e54c9bd3f6932704838fa4601a389c88c98f057 with the following preamble:

```
>>> import pyfaidx
>>> f0 = pyfaidx.Fasta('tests/data/test.fa', one_based_attributes=False)
>>> f1 = pyfaidx.Fasta('tests/data/test.fa', one_based_attributes=True)
```

I get the following issues:

1. Sequences have inconsistent names depending on whether zero-based and one-based coordinates are used:
```
>>> f0['test_chrom'][:]     
>test_chrom
ACGTACGTACGTACGTACGTACGT
>>> f1['test_chrom'][:]
>test_chrom:1-24
ACGTACGTACGTACGTACGTACGT
```

2. Using the same coordinates between "zero-based" and "one-based" objects produces the exact same results, rather than the single-base shift expected:

```
>>> f1['test_chrom'][:][1:5]
>test_chrom:2-5
CGTA
>>> f0['test_chrom'][:][1:5]
>test_chrom
CGTA
```

**Comment by mdshw5** [comment]
Thanks so much for filing a reproducible issue! I have to explain that you have discovered one bug and encountered one confusing feature. 

First, the `Sequence.longname`  method should definitely be updated to behave as you expect. 

The second issue you raise is actually expected behavior. The `one_based_attributes` argument only applies to the "friendly" coordinate representation but should have no effect on the slice notation. I should update the documentation to make this explicit. I believe that having a switch for the slicing notation would be quite confusing and allow subtle bugs to go unnoticed.

**Comment by mdshw5** [comment]
- [ ] Fix `Sequence.longname` behavior with `one_based_attributes`
- [ ] Add test case
