### ISSUE TITLE
Is the "fetch" function thread safe? 

### ISSUE THREAD

**Issue by simoncchu** [mdshw5/pyfaidx#92]
I am using the pyfaidx to index an fasta file. It works well for one process. When I run with multiple process with shared memory, the fetched records seems messed up. I am not sure whether something wrong with my code, so asking help to confirm whether I correctly use the fetch function. Here is my code:

```
import sys
import os
from Bio import SeqIO
from multiprocessing import Manager, Process
from pyfaidx import Faidx

def run_check_v2(m_fa_index, lreads, m_rslt):
    for read_id in lreads:
        rlen=m_fa_index.index[read_id].rlen
        seq= str(m_fa_index.fetch(read_id,1,rlen).seq)
        m_rslt[read_id]=seq

def check_reads_multi_threads_v2(m_fa_index, n_threads, m_rslt):
    lreads=m_fa_index.index.keys()
    processes=[]
    for i in range(n_threads):
        n_avrg=int(len(lreads)/n_threads)
        start=0
        end=0
        if i==(n_threads-1):
            start=i*n_avrg
            end=len(lreads)
        else:
            start=i*n_avrg
            end=(i+1)*n_avrg

        p = Process(target=run_check_v2, args=(m_fa_index, lreads[start:end], m_rslt))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()

    #print m_rslt
    for key in lreads:
        if m_rslt.has_key(key):
            print key, m_rslt[key]

if __name__ == "__main__":
    sf_reads=sys.argv[1]
    n_threads=int(sys.argv[2])

    manager = Manager()
    m_rslt=manager.dict()
    m_fa_index=manager.dict()

    m_fa_index = Faidx(sf_reads)
    check_reads_multi_threads_v2(m_fa_index, n_threads, m_rslt)
```

Does the `seq= str(m_fa_index.fetch(read_id,1,rlen).seq)` is correctly used? From the results, it seems it combines sequences of different reads. And have different output for different number of threads.

And if I directly read the sequences into memory and then share with different process (not index first and share the index), then the results is always correct.

**Comment by mdshw5** [comment]
I don't believe the current implementation is thread-safe, but it's unclear whether it's safe to use with multiprocessing. My gut says no because I think the file offset is stored at the OS level along with the file descriptor for the open file. That means there's a race condition for concurrent `file.seek()` and `file.read()` operations. I can try adding locks around the sensitive code to see if this is the case. I'm assuming your index file is large enough that you can't just move `Faidx(sf_reads)` inside of `run_check_v2`? If you initialize the `Faidx` object in each process separately then there will be no shared state and it's definitely thread and process safe.

**Comment by mdshw5** [comment]
If you could turn your code into a test that would help me with the thread-safe implementation.

**Comment by Reedwarbler** [comment]
Thank you @mdshw5 

I think you are right about the cause of the problem in my code. I have tested by creating the index in each process separately and it works. 

I would like to turn my code into a test. But not quite clear how to do that? Follow some policy?

**Comment by mdshw5** [comment]
Actually never mind about the test. To answer your question though, writing a test is usually just writing code that generates the incorrect output with the current version, but adding an assertion for the expected output once the issue is fixed. That way you can test new fixes quickly to check for the expected output. Also, once you've written a test you'll catch any future regressions in behavior quickly. Some test examples for this package are here: https://github.com/mdshw5/pyfaidx/blob/master/tests/test_feature_indexing.py

**Comment by Maarten-vd-Sande** [comment]
I am not sure if afed004dd8a430e4899c753e8c7e346c6a851b1a was supposed to make it thread-safe, but I still get edge cases:
```
import pyfaidx
from multiprocessing import Pool
import random

def get_random_sequence(_):
    pos = random.randint(0, len(danRer11['chr9']) - 500)
    seq = danRer11['chr9'][pos:pos+500]
    assert len(seq) == 500


danRer11 = pyfaidx.Fasta("/vol/genomes/danRer11/danRer11.fa")

# "single-thread"
print("try single-thread")
for _ in range(1000):
    get_random_sequence(None)

print("try multi-thread")
p = Pool(32)
p.map(get_random_sequence, range(1000))
```

> try single-thread
> try multi-thread
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/sande/anaconda3/envs/neural/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/sande/anaconda3/envs/neural/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "/home/sande/Dropbox/Studie/PhD/neuralnetworks/test2.py", line 18, in get_random_sequence
>     assert len(seq) == 500
> AssertionError
> """

Loading the genome in the function indeed doesn't cause any problems.

**Comment by Maarten-vd-Sande** [comment]
Btw changing the lock to a multiprocessing lock reduces the frequency of the error happening, but it still happens.. Any idea why @mdshw5

**Comment by mdshw5** [comment]
Well, I'm glad you reported this and will look in to how I can actually make the object thread-safe. To be clear I've not used my own package in a multiprocessing environment in quite a while, and so it's quite likely that it needs a few extra locks around sensitive I/O operations.

**Comment by mdshw5** [comment]
@Maarten-vd-Sande Looking more closely at the differences between synchronization in python's threading vs multiprocessing modules I'm remembering how much of a headache this actually is. I've used both modules for different tasks in the past, but for I/O-bound operations I've chosen threading due to this statement in the threading [documentation](https://docs.python.org/3.8/library/threading.html#lock-objects): 

> **CPython implementation detail**: In CPython, due to the Global Interpreter Lock, only one thread can execute Python code at once (even though certain performance-oriented libraries might overcome this limitation). If you want your application to make better use of the computational resources of multi-core machines, you are advised to use multiprocessing or concurrent.futures.ProcessPoolExecutor. However, threading is still an appropriate model if you want to run multiple I/O-bound tasks simultaneously.

The `multiprocessing.Lock` and `threading.Lock` internals are completely different since they attempt to solve different issues. Mainly it seems that `multiprocessing.Lock` must be inherited by the child processes, which makes implementation in the `Fasta` object almost impossible, since the `Fasta` instance will serialized by `pickle` before being copied to the children, rendering the lock useless (see the [multiprocessing documentation](https://docs.python.org/3.8/library/multiprocessing.html#synchronization-between-processes) for an example). 

So, I think that since I've implemented the `threading.Lock` in `Faidx.fetch` that means that `Fasta` is thread-safe but not process safe. To make the object process safe you should be able to do something like:

```python
import pyfaidx
from multiprocessing import Pool, Lock
import random

def get_random_sequence_sync(_):
    pos = random.randint(0, len(danRer11['chr9']) - 500)
    lock.acquire()
    seq = danRer11['chr9'][pos:pos+500]
    lock.release()
    assert len(seq) == 500

def init(l):
    global lock
    lock = l

danRer11 = pyfaidx.Fasta("/vol/genomes/danRer11/danRer11.fa")

print("try multi process")
p = Pool(32, initializer=init, initargs=(Lock(),))
p.map(get_random_sequence_sync, range(1000))
```
